CREATE TABLE "facilities_snapshot" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"school_id" uuid NOT NULL,
	"period_id" uuid NOT NULL,
	"classrooms_total" integer NOT NULL,
	"classrooms_good" integer NOT NULL,
	"classrooms_repair" integer NOT NULL,
	"water_source" text NOT NULL,
	"electricity_source" text NOT NULL,
	"latrines_boys" integer NOT NULL,
	"latrines_girls" integer NOT NULL,
	"latrines_staff" integer NOT NULL,
	"latrine_type" text NOT NULL,
	"handwashing" boolean NOT NULL,
	"has_library" boolean NOT NULL,
	"has_ict_lab" boolean NOT NULL,
	"internet" boolean NOT NULL,
	"has_kitchen" boolean NOT NULL,
	"gsfp_participating" boolean NOT NULL,
	"library_book_count" integer,
	"library_staff_fte" numeric(4, 1),
	"computers_total" integer,
	"computers_working" integer,
	"internet_type" text,
	"meals_served_last_term" integer,
	"pupils_fed_daily_avg" integer,
	"caterer_name" text,
	"textbook_availability" text,
	"student_desks_usable" integer,
	"student_desks_broken" integer,
	"teacher_desks" integer,
	"chalkboards" integer,
	"whiteboards" integer,
	"projectors" integer,
	"note" text,
	"captured_at" timestamp with time zone DEFAULT now() NOT NULL,
	"captured_by" uuid,
	CONSTRAINT "uniq_facilities_snapshot_term" UNIQUE("school_id","period_id"),
	CONSTRAINT "facilities_snapshot_classrooms_nonneg" CHECK ("facilities_snapshot"."classrooms_total" >= 0 AND "facilities_snapshot"."classrooms_good" >= 0 AND "facilities_snapshot"."classrooms_repair" >= 0),
	CONSTRAINT "facilities_snapshot_classrooms_sum" CHECK ("facilities_snapshot"."classrooms_good" + "facilities_snapshot"."classrooms_repair" <= "facilities_snapshot"."classrooms_total"),
	CONSTRAINT "facilities_snapshot_water_source_valid" CHECK ("facilities_snapshot"."water_source" IN ('BOREHOLE', 'PIPE', 'WELL', 'NONE')),
	CONSTRAINT "facilities_snapshot_electricity_source_valid" CHECK ("facilities_snapshot"."electricity_source" IN ('GRID', 'SOLAR', 'GENERATOR', 'NONE')),
	CONSTRAINT "facilities_snapshot_latrines_nonneg" CHECK ("facilities_snapshot"."latrines_boys" >= 0 AND "facilities_snapshot"."latrines_girls" >= 0 AND "facilities_snapshot"."latrines_staff" >= 0),
	CONSTRAINT "facilities_snapshot_latrine_type_valid" CHECK ("facilities_snapshot"."latrine_type" IN ('WC', 'KVIP', 'PIT', 'NONE')),
	CONSTRAINT "facilities_snapshot_library_nonneg" CHECK ("facilities_snapshot"."library_book_count" >= 0 AND "facilities_snapshot"."library_staff_fte" >= 0),
	CONSTRAINT "facilities_snapshot_computers_nonneg" CHECK ("facilities_snapshot"."computers_total" >= 0 AND "facilities_snapshot"."computers_working" >= 0),
	CONSTRAINT "facilities_snapshot_computers_bound" CHECK ("facilities_snapshot"."computers_working" IS NULL OR "facilities_snapshot"."computers_total" IS NULL OR "facilities_snapshot"."computers_working" <= "facilities_snapshot"."computers_total"),
	CONSTRAINT "facilities_snapshot_gsfp_nonneg" CHECK ("facilities_snapshot"."meals_served_last_term" >= 0 AND "facilities_snapshot"."pupils_fed_daily_avg" >= 0),
	CONSTRAINT "facilities_snapshot_furniture_nonneg" CHECK ("facilities_snapshot"."student_desks_usable" >= 0 AND "facilities_snapshot"."student_desks_broken" >= 0 AND "facilities_snapshot"."teacher_desks" >= 0 AND "facilities_snapshot"."chalkboards" >= 0 AND "facilities_snapshot"."whiteboards" >= 0 AND "facilities_snapshot"."projectors" >= 0),
	CONSTRAINT "facilities_snapshot_textbook_availability_valid" CHECK ("facilities_snapshot"."textbook_availability" IN ('ADEQUATE', 'INADEQUATE'))
);
--> statement-breakpoint
ALTER TABLE "facilities_snapshot" ADD CONSTRAINT "facilities_snapshot_school_id_ref_school_id_fk" FOREIGN KEY ("school_id") REFERENCES "public"."ref_school"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "facilities_snapshot" ADD CONSTRAINT "facilities_snapshot_captured_by_ref_user_id_fk" FOREIGN KEY ("captured_by") REFERENCES "public"."ref_user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "facilities_snapshot" ADD CONSTRAINT "facilities_snapshot_school_id_period_id_academic_period_school_id_period_id_fk" FOREIGN KEY ("school_id","period_id") REFERENCES "public"."academic_period"("school_id","period_id") ON DELETE cascade ON UPDATE no action;